<?php

/**
 * @file
 * Primary module hooks for Commerce recurring role module.
 *
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter() for
 * 'commerce_product_variation_type_form'.
 *
 * @param array $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 */
function commerce_recurring_role_form_commerce_product_variation_type_form_alter(array &$form, FormStateInterface $form_state) {
  if (!isset($form['traits']['#options']['purchasable_entity_subscription_role'])) {
    return;
  }

  $form['traits']['purchasable_entity_subscription_role'] = [
    '#states' => [
      'enabled' => [
        ':input[name="traits[purchasable_entity_subscription]"]' => ['checked' => TRUE],
      ],
      'unchecked' => [
        ':input[name="traits[purchasable_entity_subscription_role]"]' => ['disabled' => TRUE],
      ],
    ],
  ];
}

/**
 * Implements hook_form_FORM_ID_alter() for
 * 'commerce_product_variation_form'.
 *
 * @param array $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 */
function commerce_recurring_role_form_commerce_product_variation_form_alter(array &$form, FormStateInterface $form_state) {
  if (!$form_state->getFormObject()->getEntity()->hasField('role')) {
    unset($form['subscription_type']['widget'][0]['target_plugin_id']['#options']['product_variation_role']);
  }
  else {
    unset($form['subscription_type']['widget'][0]['target_plugin_id']['#options']['product_variation']);
  }
}

